ALTER TABLE locations    ADD COLUMN IF NOT EXISTS latitude  DOUBLE PRECISION;
ALTER TABLE locations    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS latitude  DOUBLE PRECISION;
ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS location_accuracy DOUBLE PRECISION;
