// Expo config plugin: app-wide Android FLAG_SECURE on release builds.
//
// FLAG_SECURE is a window flag (blocks screenshots + hides the app content in
// the recent-apps switcher and from screen recording). There is NO manifest
// attribute for it — it must be set on the Activity window in native code, so a
// config plugin that patches MainActivity.onCreate is the only durable way (the
// android/ dir is regenerated by `expo prebuild`).
//
// Scope: applied APP-WIDE (the single MainActivity hosts every RN screen) and
// ONLY on release builds (guarded by `!BuildConfig.DEBUG`) so screenshots /
// screen-record still work in dev. Per-SCREEN granularity (e.g. secure only on
// login / checkout / item-detail) would require toggling the flag from JS via a
// native module and is a documented follow-up — see plan item #7.
//
// Verify: `npx expo prebuild -p android --clean`, then inspect
// android/app/src/main/java/com/inventorypro/app/MainActivity.kt for the
// FLAG_SECURE block. On a release install, screenshots are blocked and the
// recent-apps preview is blank.

const { withMainActivity } = require('expo/config-plugins');

const MARKER = '// @generated-flag-secure';
const IMPORT_LINE = 'import android.view.WindowManager';

const FLAG_SECURE_BLOCK = `    ${MARKER}: block screenshots / recent-apps preview on release builds
    if (!BuildConfig.DEBUG) {
      window.setFlags(
        WindowManager.LayoutParams.FLAG_SECURE,
        WindowManager.LayoutParams.FLAG_SECURE
      )
    }`;

function injectFlagSecure(contents) {
  // Idempotent.
  if (contents.includes(MARKER)) {
    return contents;
  }

  let next = contents;

  // 1. Ensure the WindowManager import exists (BuildConfig is same-package, no
  //    import needed).
  if (!next.includes(IMPORT_LINE)) {
    if (!/^import android\.os\.Bundle$/m.test(next)) {
      throw new Error(
        'withReleaseFlagSecure: could not find `import android.os.Bundle` to anchor the WindowManager import',
      );
    }
    next = next.replace(
      /^import android\.os\.Bundle$/m,
      `import android.os.Bundle\n${IMPORT_LINE}`,
    );
  }

  // 2. Insert the FLAG_SECURE block right after `super.onCreate(null)` in
  //    onCreate (Expo's generated MainActivity calls super.onCreate(null)).
  const superCreateRe = /(super\.onCreate\(null\))/;
  if (!superCreateRe.test(next)) {
    throw new Error(
      'withReleaseFlagSecure: could not find `super.onCreate(null)` in MainActivity',
    );
  }
  next = next.replace(superCreateRe, `$1\n${FLAG_SECURE_BLOCK}`);

  return next;
}

module.exports = function withReleaseFlagSecure(config) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        `withReleaseFlagSecure: expected Kotlin MainActivity, got ${cfg.modResults.language}`,
      );
    }
    cfg.modResults.contents = injectFlagSecure(cfg.modResults.contents);
    return cfg;
  });
};
