// Expo config plugin: durable Android release signing.
//
// `android/` is gitignored and regenerated by `expo prebuild`, so the hand patch
// applied to android/app/build.gradle does NOT survive a clean prebuild. This
// plugin re-applies that exact patch at prebuild time via a withAppBuildGradle
// mod, so the release signingConfig is injected every time android/ is generated.
//
// Signing material is sourced from a gitignored android/keystore.properties
// (keys: storeFile, storePassword, keyAlias, keyPassword — same as the local
// patch and apps/mobile/credentials.json). NOTHING secret lives in this file.
// When keystore.properties is absent (CI / fresh clones), release falls back to
// the debug signingConfig so the build still succeeds.
//
// Verify: `npx expo prebuild -p android --clean` then inspect
// android/app/build.gradle — it should contain the release signingConfig block
// and the ternary on buildTypes.release. `./gradlew :app:assembleRelease` with
// android/keystore.properties present signs with the real keystore.

const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @generated-release-signing';

// Loads keystore.properties (gitignored) before the top-level `android {` block.
const KEYSTORE_LOADER = `${MARKER}: load release keystore from gitignored android/keystore.properties (not committed)
def ksPropsFile = rootProject.file('keystore.properties')
def ksProps = new Properties()
if (ksPropsFile.exists()) {
    ksProps.load(new FileInputStream(ksPropsFile))
}

`;

// release signingConfig, injected as a sibling of the default `debug` config.
const RELEASE_SIGNING_CONFIG = `        release {
            // Sourced from the gitignored android/keystore.properties. Only
            // populated (and only referenced by buildTypes.release) when present.
            if (ksPropsFile.exists()) {
                storeFile file(ksProps['storeFile'])
                storePassword ksProps['storePassword']
                keyAlias ksProps['keyAlias']
                keyPassword ksProps['keyPassword']
            }
        }
`;

// Real keystore when keystore.properties exists, else debug fallback.
const RELEASE_BUILDTYPE_SIGNING =
  'signingConfig ksPropsFile.exists() ? signingConfigs.release : signingConfigs.debug';

function injectReleaseSigning(contents) {
  // Idempotent: if our marker is already present, leave the file untouched.
  if (contents.includes(MARKER)) {
    return contents;
  }

  let next = contents;

  // 1. Insert the keystore.properties loader before the top-level `android {`.
  if (!/^android \{/m.test(next)) {
    throw new Error(
      "withReleaseSigning: could not find top-level `android {` block in build.gradle",
    );
  }
  next = next.replace(/^android \{/m, `${KEYSTORE_LOADER}android {`);

  // 2. Add the `release` signingConfig as a sibling of `debug` inside
  //    signingConfigs { ... }.
  if (!/signingConfigs\s*\{/.test(next)) {
    throw new Error(
      'withReleaseSigning: could not find `signingConfigs {` block in build.gradle',
    );
  }
  next = next.replace(/signingConfigs\s*\{\n/, (m) => `${m}${RELEASE_SIGNING_CONFIG}`);

  // 3. Point buildTypes.release at the real keystore (with debug fallback).
  //    Match the FIRST `signingConfig signingConfigs.debug` that appears after
  //    the release buildType opens — the debug buildType (which also uses
  //    signingConfigs.debug) precedes it, so the non-greedy match lands on the
  //    release one.
  const releaseSigningRe =
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/;
  if (!releaseSigningRe.test(next)) {
    throw new Error(
      'withReleaseSigning: could not find release buildType signingConfig in build.gradle',
    );
  }
  next = next.replace(releaseSigningRe, `$1${RELEASE_BUILDTYPE_SIGNING}`);

  return next;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withReleaseSigning: expected groovy build.gradle, got ${cfg.modResults.language}`,
      );
    }
    cfg.modResults.contents = injectReleaseSigning(cfg.modResults.contents);
    return cfg;
  });
};
