// Dev tool (#24): populate the LOCAL database with sample locations, items, and
// stock so a tester has data to exercise the UI against.
//
// SANDBOX-ONLY BY DESIGN. This refuses to run unless the caller is on a test
// account (users.is_test). Test accounts are read-only on the server — their
// /sync/push is 403'd — so this deliberately writes ONLY to the local SQLite
// (upsert*, no appendOutbox): the rows appear immediately in the UI, never reach
// production, and never leave a stuck outbox entry behind. That is the whole
// point of the test-account guard the caller enforces.

import { generateUUID } from '../utils/uuid';
import { runInTransaction } from '../db/tx';
import { upsertLocation, type Location } from '../db/queries/locations';
import { upsertItem, adjustStock, type InventoryItem } from '../db/queries/items';
import { PRODUCT_CLASS_IDS } from '../constants/units';
import { colors } from '../theme';

export interface SampleDataResult {
  locations: number;
  items: number;
  stockRows: number;
}

// Restoration-industry-flavored sample names, indexed so a run of N is varied
// and its rows are obviously synthetic ("Sample …").
const LOCATION_NAMES = [
  'Sample Warehouse', 'Sample Box Truck', 'Sample Storage Locker', 'Sample Job Trailer',
  'Sample Supply Van', 'Sample Shop', 'Sample Staging Area', 'Sample Overflow Bay',
];
const ITEM_NAMES = [
  'Sample Air Mover', 'Sample Dehumidifier', 'Sample HEPA Filter', 'Sample Nitrile Gloves',
  'Sample Poly Sheeting', 'Sample Antimicrobial', 'Sample Moisture Meter', 'Sample Extension Cord',
];

const pick = (arr: string[], i: number) =>
  `${arr[i % arr.length]}${i >= arr.length ? ` ${Math.floor(i / arr.length) + 1}` : ''}`;

/**
 * Generate `count` sample locations and `count` sample items (each with a little
 * starting stock at one of the generated locations). Local-only writes.
 *
 * @throws if `isTest` is false — this must never run on a real account.
 */
export function generateSampleData(opts: {
  isTest: boolean;
  count?: number;
}): SampleDataResult {
  if (!opts.isTest) {
    throw new Error(
      'Sample data generation is only available on a test/sandbox account, so it can never reach production.',
    );
  }
  // Clamp to a sane range: enough to be useful, never enough to bog the device.
  const count = Math.max(1, Math.min(opts.count ?? 5, 25));
  const now = new Date().toISOString();

  let stockRows = 0;
  const locationIds: string[] = [];

  runInTransaction(() => {
    for (let i = 0; i < count; i++) {
      const id = generateUUID();
      locationIds.push(id);
      const loc: Location = {
        id,
        name: pick(LOCATION_NAMES, i),
        parent_id: null,
        color: colors.brand,
        icon: '📦',
        owner_user_id: null,
        active: 1,
        updated_at: now,
        synced_at: null,
      };
      upsertLocation(loc);
    }

    for (let i = 0; i < count; i++) {
      const id = generateUUID();
      const item: InventoryItem = {
        id,
        name: pick(ITEM_NAMES, i),
        barcode: null,
        description: 'Generated by the sample-data dev tool.',
        sku: null,
        supplier: null,
        model: null,
        kind: 'product',
        category: null,
        returnable: 0,
        unit_tracked: 0,
        tag_prefix: null,
        // A real product_class id so formatQuantity's decimals stay correct.
        unit_category: PRODUCT_CLASS_IDS.piece,
        unit: 'each',
        min_qty_alert: 0,
        reorder_to: null,
        active: 1,
        updated_at: now,
        synced_at: null,
        home_location_id: null,
        pack_size: null,
      };
      upsertItem(item);

      // Seed a bit of stock at one of the generated locations so the item shows
      // an on-hand quantity somewhere.
      const locId = locationIds[i % locationIds.length];
      if (locId) {
        adjustStock(id, locId, 10 + (i % 5) * 5);
        stockRows++;
      }
    }
  });

  return { locations: count, items: count, stockRows };
}
